run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unconvert
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: indent-error-flow
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-naming
      - name: var-declaration
